#!/usr/bin/env python3
"""Convert our out/symbols.csv into the symbol-address format splat consumes.

This is the interchange format the upstream decomp keeps in
config/symbols/<unit>.txt:

    _start = 0x00200008; // type:func size:0xAC

Our symbols.csv is the richer artifact -- it carries binding and section index
for all six binaries in one table -- but this format is what splat, and
therefore any splat-based decomp tree, can ingest directly. Emitting it means
our symbol work is usable upstream without anyone re-deriving it.

Usage:
  ./symbols_to_splat.py --binary SLUS_204.69 -o main.txt
  ./symbols_to_splat.py --all --outdir config/symbols/
  ./symbols_to_splat.py --binary OV11.OVL --locals -o ov11.txt

By default only GLOBAL symbols are emitted, since a file-local static's name is
only meaningful inside its own translation unit and GCC 2.x mangles it anyway
(`sSemaParam` becomes `sSemaParam.0`). Pass --locals to include them, with the
suffix preserved.
"""
from __future__ import annotations

import argparse
import collections
import csv
import os
import sys
from pathlib import Path

# Set DECOMP_GAME_DIR to the directory holding your symbols.csv, or pass --csv.
DEFAULT_CSV = Path(os.environ.get("DECOMP_GAME_DIR", ".")) / "symbols.csv"

# out/DECOMP-PLAN.md §0: the overlays all load at 0xa00000 and are mutually
# exclusive at runtime, so each one gets its own symbol file.
UNIT_FOR = {
    "SLUS_204.69": "main",
    "OV01.OVL": "ov01",
    "OV02.OVL": "ov02",
    "OV10.OVL": "ov10",
    "OV11.OVL": "ov11",
    "OV12.OVL": "ov12",
}

TYPE_MAP = {"FUNC": "func", "OBJECT": "object"}

# Below this is not an EE address: SLUS .text starts at 0x200000 and the
# overlays load at 0xa00000 (out/TOOLCHAIN.md).
EE_LOAD_FLOOR = 0x100000


def rows(csv_path: Path, binary: str, want_locals: bool):
    """Collect emittable symbols, dropping anything a flat namespace can't hold.

    Returns (entries, dropped) where dropped explains each exclusion class.
    A splat symbol file is one flat namespace, but the ELF symtab is not: two
    translation units can each have a `static int tbl`, and the SLUS also
    embeds a copy of the ov02 section at 0xa00000, so generic local names like
    buffer/copyframe/pi/tbl/force_to_data genuinely occur at several addresses.
    Emitting whichever came first would silently assert a wrong address, so
    ambiguous names are dropped and counted instead.
    """
    by_name: dict[str, set[int]] = collections.defaultdict(set)
    rows_seen = []
    with open(csv_path) as fh:
        for r in csv.DictReader(fh):
            if r["binary"] != binary:
                continue
            if r["bind"] != "GLOBAL" and not want_locals:
                continue
            name = r["name"]
            # Compiler breadcrumbs, not real symbols.
            if name in ("gcc2_compiled.", "__gnu_compiled_c") or not name:
                continue
            # $L123 / $LC4 are the assembler's own branch and constant labels.
            if name.startswith("$"):
                continue
            va, size = int(r["va"], 16), int(r["size"])
            # The Vu0*/Vu1Mem*/GsKick family are offsets into VU memory -- a
            # separate address space, so their values are small (0x0, 0x20,
            # 0x28...). EE code and data start at 0x200000 for the main ELF and
            # 0xa00000 for the overlays, so anything below the EE load area is
            # not an EE address and would poison a splat symbol file. Upstream
            # keeps these in a dedicated <unit>.vuN-symbols.ld instead.
            if va < EE_LOAD_FLOOR:
                continue
            by_name[name].add(va)
            rows_seen.append((va, name, size, r["type"]))

    ambiguous = {n for n, vas in by_name.items() if len(vas) > 1}
    out, emitted = [], set()
    for va, name, size, typ in rows_seen:
        if name in ambiguous or name in emitted:
            continue
        emitted.add(name)
        out.append((va, name, size, typ))
    out.sort(key=lambda t: (t[0], t[1]))
    return out, sorted(ambiguous)


def write(entries, binary: str, path, want_locals: bool):
    lines = [
        "// Generated by compat/symbols_to_splat.py from out/symbols.csv.",
        f"// {binary}: {len(entries)} symbols"
        + (" (globals and file-locals)" if want_locals else " (globals only)"),
        "",
    ]
    for va, name, size, typ in entries:
        note = []
        if typ in TYPE_MAP:
            note.append(f"type:{TYPE_MAP[typ]}")
        if size:
            note.append(f"size:{size:#X}".replace("0X", "0x"))
        comment = f"  // {' '.join(note)}" if note else ""
        lines.append(f"{name} = 0x{va:08X};{comment}")
    text = "\n".join(lines) + "\n"
    if path is None or str(path) == "-":
        sys.stdout.write(text)
    else:
        Path(path).write_text(text)
    return len(entries)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    ap.add_argument("--binary", help="one of: " + ", ".join(UNIT_FOR))
    ap.add_argument("--all", action="store_true", help="emit every binary")
    ap.add_argument("--outdir", type=Path, help="with --all: write <unit>.txt here")
    ap.add_argument("-o", "--out", help="output file, or - for stdout")
    ap.add_argument("--locals", action="store_true",
                    help="also emit LOCAL symbols (names keep GCC's .N suffix)")
    args = ap.parse_args()

    if not args.csv.exists():
        print(f"no symbol table at {args.csv}", file=sys.stderr)
        return 2
    if not args.all and not args.binary:
        ap.error("pass --binary <name> or --all")

    if args.all:
        if not args.outdir:
            ap.error("--all requires --outdir")
        args.outdir.mkdir(parents=True, exist_ok=True)
        total = 0
        for binary, unit in UNIT_FOR.items():
            entries, ambiguous = rows(args.csv, binary, args.locals)
            if not entries:
                print(f"  {binary:<14} no rows -- skipped", file=sys.stderr)
                continue
            n = write(entries, binary, args.outdir / f"{unit}.txt", args.locals)
            extra = f"  (+{len(ambiguous)} ambiguous dropped)" if ambiguous else ""
            print(f"  {unit}.txt  {n} symbols  ({binary}){extra}")
            total += n
        print(f"total {total} symbols")
        return 0

    if args.binary not in UNIT_FOR:
        print(f"unknown binary {args.binary!r}; expected one of {', '.join(UNIT_FOR)}",
              file=sys.stderr)
        return 2
    entries, ambiguous = rows(args.csv, args.binary, args.locals)
    n = write(entries, args.binary, args.out or "-", args.locals)
    if args.out and args.out != "-":
        print(f"wrote {args.out}: {n} symbols")
    if ambiguous:
        print(f"dropped {len(ambiguous)} name(s) held by more than one address: "
              + ", ".join(ambiguous[:8]) + ("..." if len(ambiguous) > 8 else ""),
              file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
